# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='dormitory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='room',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
