# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 14:23
from __future__ import unicode_literals

import app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_printing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fradmin', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('room', models.CharField(blank=True, max_length=15)),
                ('phonenumber', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='printing',
            name='user',
        ),
        migrations.AddField(
            model_name='printing',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Client'),
        ),
        migrations.AddField(
            model_name='printing',
            name='file',
            field=models.FileField(null=True, upload_to='', validators=[app.validators.validate_file]),
        ),
        migrations.AddField(
            model_name='printing',
            name='num_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dormitory'),
        ),
        migrations.AlterField(
            model_name='client',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University'),
        ),
        migrations.AddField(
            model_name='franchiseadmin',
            name='dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.University'),
        ),
        migrations.AddField(
            model_name='franchiseadmin',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Dormitory'),
        ),
        migrations.AddField(
            model_name='franchiseadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.University'),
        ),
        migrations.AddField(
            model_name='manager',
            name='dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Dormitory'),
        ),
        migrations.AddField(
            model_name='manager',
            name='fradmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FranchiseAdmin'),
        ),
    ]
