# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170804_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='university',
            new_name='name',
        ),
    ]
