# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170804_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Dormitory'),
        ),
        migrations.AlterField(
            model_name='client',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.University'),
        ),
    ]
