# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('app', '0010_auto_20170804_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='printing',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Manager'),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
