# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170804_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiseadmin',
            name='dormitory',
        ),
        migrations.AddField(
            model_name='dormitory',
            name='fadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FranchiseAdmin'),
        ),
        migrations.AlterField(
            model_name='franchiseadmin',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.University'),
        ),
    ]
