# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170805_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
