# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170805_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
