# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_manager_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiseadmin',
            name='is_fradmin',
        ),
    ]
